# Generated by Django 4.2.10 on 2024-02-11 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0004_mealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ydd_db.mealtype'),
        ),
    ]
