# Generated by Django 4.2.10 on 2024-02-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0005_meal_type'),
        ('ydd_db', '0005_meal_type_alter_meal_meal_type'),
    ]

    operations = [
    ]
