# Generated by Django 4.2.10 on 2024-02-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0006_merge_20240211_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ydd_db.mealtype'),
        ),
    ]
