# Generated by Django 4.2.10 on 2024-02-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0008_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='identification',
        ),
    ]
