# Generated by Django 4.2.10 on 2024-02-17 20:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ydd_db', '0010_delete_botuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_code', models.CharField(max_length=20, unique=True)),
                ('bot_username', models.CharField(max_length=100)),
                ('bot_user_id', models.CharField(max_length=20, unique=True)),
                ('bot_created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_updated_at', models.DateTimeField(auto_now=True)),
                ('bot_valid_till', models.DateTimeField(default=datetime.datetime(2024, 2, 27, 20, 57, 39, 142822, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['bot_valid_till'],
            },
        ),
    ]
