# Generated by Django 4.2.10 on 2024-02-17 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0011_botuserdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuserdata',
            name='bot_user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='botuserdata',
            name='bot_valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 21, 55, 46, 541594, tzinfo=datetime.timezone.utc)),
        ),
    ]
