# Generated by Django 4.2.10 on 2024-02-17 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0012_alter_botuserdata_bot_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuserdata',
            name='bot_valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 23, 12, 58, 470305, tzinfo=datetime.timezone.utc)),
        ),
    ]
