# Generated by Django 4.2.10 on 2024-02-17 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0013_alter_botuserdata_bot_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuserdata',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botuserdata',
            name='requests_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='botuserdata',
            name='bot_valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 23, 15, 20, 874079, tzinfo=datetime.timezone.utc)),
        ),
    ]
