# Generated by Django 4.2.10 on 2024-02-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydd_db', '0015_alter_botuserdata_bot_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuserdata',
            name='bot_valid_till',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
